import {
  clearAllWeightData,
  clearWeightGoal,
  getWeightGoal,
  listWeightEntries,
  saveWeightEntry,
  saveWeightGoal,
  softDeleteWeightEntry,
  getFirstUser,
  getUserByExternalId,
  getUserSettings,
  saveUserSettings,
  upsertUser,
} from "./supabaseUserStore";
import {
  addFoodItem,
  addQuickAddFoodLog,
  addUserFoodLog,
  copyFoodLogsFromDate,
  createUserRecipe,
  deleteFoodItem,
  deleteUserRecipe,
  deleteUserFoodLog,
  getFavoriteFoodIds,
  getFavoriteFoodItems,
  getFoodItemByBarcode,
  getFoodItemById,
  getRecentFoodItems,
  getUserFoodLogEntriesByDate,
  getUserFoodLogEntryById,
  getUserRecipeDetailsById,
  listFoodItems,
  saveFoodItem,
  searchFoodItems,
  setFoodItemFavorite,
  updateQuickAddFoodLog,
  updateUserFoodLog,
  updateUserRecipe,
} from "./supabaseFoodStore";

export const DB = {
  addUser: upsertUser,
  getUser: getFirstUser,
  getUserByExternalId,
  getUserSettings,
  saveUserSettings,
  listWeightEntries,
  saveWeightEntry,
  softDeleteWeightEntry,
  clearAllWeightData,
  getWeightGoal,
  saveWeightGoal,
  clearWeightGoal,
  saveFoodItem,
  addFoodItem,
  listFoodItems,
  getFoodItemById,
  getFoodItemByBarcode,
  deleteFoodItem,
  searchFoodItems,
  getFavoriteFoodIds,
  getFavoriteFoodItems,
  getRecentFoodItems,
  setFoodItemFavorite,
  createUserRecipe,
  getUserRecipeDetailsById,
  updateUserRecipe,
  deleteUserRecipe,
  addQuickAddFoodLog,
  addUserFoodLog,
  updateUserFoodLog,
  updateQuickAddFoodLog,
  deleteUserFoodLog,
  getUserFoodLogEntryById,
  getUserFoodLogEntriesByDate,
  copyFoodLogsFromDate,
};
