import {
  addWeightLog,
  clearAllWeightData,
  clearWeightGoal,
  getRecentWeightLogs,
  getWeightGoal,
  listWeightEntries,
  saveWeightEntry,
  saveWeightGoal,
  softDeleteWeightEntry,
} from "./weightRepository";
import { getFirstUser, getUserByExternalId, upsertUser } from "./userRepository";
import { getUserSettings, saveUserSettings } from "./userSettingsRepository";
import {
  addFoodItem,
  deleteFoodItem,
  getFavoriteFoodIds,
  getFavoriteFoodItems,
  getFoodItemByBarcode,
  getFoodItemById,
  getRecentFoodItems,
  listFoodItems,
  saveFoodItem,
  searchFoodItems,
  setFoodItemFavorite,
} from "./foodRepository";
import {
  createUserRecipe,
  deleteUserRecipe,
  getUserRecipeDetailsById,
  updateUserRecipe,
} from "./recipeRepository";
import {
  addCustomMeal,
  addQuickAddFoodLog,
  addUserFoodLog,
  copyFoodLogsFromDate,
  deleteCustomMeal,
  deleteUserFoodLog,
  getCustomMeals,
  getUserFoodLogEntriesByDate,
  getUserFoodLogEntryById,
  updateQuickAddFoodLog,
  updateUserFoodLog,
} from "./foodLogRepository";

export const DB = {
  addUser: upsertUser,
  getUser: getFirstUser,
  getUserByExternalId,
  getUserSettings,
  saveUserSettings,
  addWeightLog,
  getRecentWeightLogs,
  listWeightEntries,
  saveWeightEntry,
  softDeleteWeightEntry,
  clearAllWeightData,
  getWeightGoal,
  saveWeightGoal,
  clearWeightGoal,
  saveFoodItem,
  addFoodItem,
  listFoodItems,
  getFoodItemById,
  getFoodItemByBarcode,
  deleteFoodItem,
  searchFoodItems,
  getFavoriteFoodIds,
  getFavoriteFoodItems,
  getRecentFoodItems,
  setFoodItemFavorite,
  createUserRecipe,
  getUserRecipeDetailsById,
  updateUserRecipe,
  deleteUserRecipe,
  addQuickAddFoodLog,
  addUserFoodLog,
  updateUserFoodLog,
  updateQuickAddFoodLog,
  deleteUserFoodLog,
  getUserFoodLogEntryById,
  getUserFoodLogEntriesByDate,
  copyFoodLogsFromDate,
  getCustomMeals,
  addCustomMeal,
  deleteCustomMeal,
};
