import type { DBFoodNutrientDetails } from "../../store/DB_TYPES";

// Mirrors the additive nutrient fields in the food API contract.
const NUTRIENT_KEYS = [
  "fiberG",
  "sugarG",
  "addedSugarsG",
  "waterG",
  "alcoholG",
  "saltG",
  "fatSaturatedG",
  "fatMonounsaturatedG",
  "fatPolyunsaturatedG",
  "fatTransG",
  "omega3G",
  "omega6G",
  "epaG",
  "dhaG",
  "alaG",
  "linoleicAcidG",
  "alphaLinolenicAcidG",
  "cholesterolMg",
  "vitaminAUg",
  "vitaminCMg",
  "vitaminDUg",
  "vitaminEMg",
  "vitaminKUg",
  "vitaminK1Ug",
  "vitaminK2Ug",
  "thiaminB1Mg",
  "riboflavinB2Mg",
  "niacinB3Mg",
  "pantothenicAcidB5Mg",
  "vitaminB6Mg",
  "biotinB7Ug",
  "folateB9Ug",
  "vitaminB12Ug",
  "cholineMg",
  "calciumMg",
  "ironMg",
  "magnesiumMg",
  "phosphorusMg",
  "potassiumMg",
  "sodiumMg",
  "zincMg",
  "copperMg",
  "manganeseMg",
  "seleniumUg",
  "iodineUg",
  "chromiumUg",
  "molybdenumUg",
  "histidineG",
  "isoleucineG",
  "leucineG",
  "lysineG",
  "methionineG",
  "phenylalanineG",
  "threonineG",
  "tryptophanG",
  "valineG",
  "alanineG",
  "arginineG",
  "asparticAcidG",
  "cysteineG",
  "glutamicAcidG",
  "glycineG",
  "prolineG",
  "serineG",
  "tyrosineG",
  "caffeineMg",
  "betaineMg",
  "luteinZeaxanthinUg",
] as const satisfies readonly (keyof DBFoodNutrientDetails)[];

export function foodNutrientDetails(food: Partial<DBFoodNutrientDetails>): DBFoodNutrientDetails {
  return Object.fromEntries(NUTRIENT_KEYS.map((key) => [key, food[key] ?? null])) as DBFoodNutrientDetails;
}
