-- Hybrid Pilot -> Supabase primary schema
-- Recommended server model:
-- 1. food_items = shared public catalog, insertable by signed-in users, not editable by normal users
-- 2. custom_recipes + custom_meals = public by default, editable only by original creator
-- 3. user_food_entries = private per-user food diary entries referencing catalog items / meals / recipes
-- 4. app_kv and session caching stay local on device, not in Supabase

set check_function_bodies = off;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.iso_text_date_prefix(value text)
returns date
language sql
immutable
returns null on null input
as $$
  select make_date(
    substring(value from 1 for 4)::integer,
    substring(value from 6 for 2)::integer,
    substring(value from 9 for 2)::integer
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (
    id,
    display_name,
    email,
    created_at,
    updated_at
  )
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data ->> 'name',
      new.raw_user_meta_data ->> 'full_name',
      split_part(coalesce(new.email, ''), '@', 1),
      'User'
    ),
    new.email,
    coalesce(new.created_at, now()),
    now()
  )
  on conflict (id) do update
  set
    email = excluded.email,
    updated_at = now();

  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text,
  email text,
  birthdate date,
  gender text check (gender in ('male', 'female', 'other') or gender is null),
  height_cm double precision,
  activity_level text,
  goal text,
  goal_strategy text,
  training_types jsonb not null default '[]'::jsonb,
  protein_focus text check (
    protein_focus in ('mild', 'moderate', 'focused', 'heavy')
    or protein_focus is null
  ),
  calorie_allowance integer,
  protein_g double precision,
  carbs_g double precision,
  fat_g double precision,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_training_types_is_array
    check (jsonb_typeof(training_types) = 'array')
);

alter table public.profiles
  add column if not exists goal_strategy text;

alter table public.profiles
  drop constraint if exists profiles_goal_strategy_valid;

alter table public.profiles
  add constraint profiles_goal_strategy_valid
    check (
      goal_strategy in (
        'deficit_light',
        'deficit_normal',
        'deficit_aggressive',
        'maintain',
        'surplus_light',
        'surplus_normal',
        'surplus_aggressive'
      )
      or goal_strategy is null
    );

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create table if not exists public.user_settings (
  user_id uuid primary key references public.profiles (id) on delete cascade,
  food_diary_start_hour integer not null default 7 check (food_diary_start_hour between 0 and 23),
  food_diary_end_hour integer not null default 22 check (food_diary_end_hour between 0 and 23),
  daily_calorie_overrides jsonb,
  adaptive_calories_enabled boolean not null default false,
  adaptive_mode text not null default 'recommend' check (
    adaptive_mode in ('recommend', 'auto_apply')
  ),
  adaptive_last_calculated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_settings_hours_valid check (food_diary_end_hour > food_diary_start_hour),
  constraint user_settings_daily_overrides_is_array
    check (
      daily_calorie_overrides is null
      or jsonb_typeof(daily_calorie_overrides) = 'array'
    )
);

alter table public.user_settings
  add column if not exists adaptive_calories_enabled boolean not null default false;

alter table public.user_settings
  add column if not exists adaptive_mode text not null default 'recommend'
    check (adaptive_mode in ('recommend', 'auto_apply'));

alter table public.user_settings
  add column if not exists adaptive_last_calculated_at timestamptz;

create table if not exists public.food_items (
  id bigint generated by default as identity primary key,
  submitted_by_user_id uuid references public.profiles (id) on delete set null,
  source text not null check (
    source in ('custom', 'manual', 'open_food_facts', 'import', 'usda')
  ),
  source_id text,
  barcode text,
  name text not null,
  brand_name text,
  image_url text,
  quantity_value double precision,
  quantity_unit text,
  serving_size_value double precision,
  serving_size_unit text,
  nutrition_basis text not null default 'serving' check (
    nutrition_basis in ('100g', '100ml', 'serving')
  ),
  calories double precision,
  protein_g double precision,
  carbs_g double precision,
  fat_g double precision,
  fiber_g double precision,
  sugar_g double precision,
  added_sugars_g double precision,
  water_g double precision,
  alcohol_g double precision,
  salt_g double precision,
  fat_saturated_g double precision,
  fat_monounsaturated_g double precision,
  fat_polyunsaturated_g double precision,
  fat_trans_g double precision,
  omega3_g double precision,
  omega6_g double precision,
  epa_g double precision,
  dha_g double precision,
  ala_g double precision,
  linoleic_acid_g double precision,
  alpha_linolenic_acid_g double precision,
  cholesterol_mg double precision,
  vitamin_a_ug double precision,
  vitamin_c_mg double precision,
  vitamin_d_ug double precision,
  vitamin_e_mg double precision,
  vitamin_k_ug double precision,
  vitamin_k1_ug double precision,
  vitamin_k2_ug double precision,
  thiamin_b1_mg double precision,
  riboflavin_b2_mg double precision,
  niacin_b3_mg double precision,
  pantothenic_acid_b5_mg double precision,
  vitamin_b6_mg double precision,
  biotin_b7_ug double precision,
  folate_b9_ug double precision,
  vitamin_b12_ug double precision,
  choline_mg double precision,
  calcium_mg double precision,
  iron_mg double precision,
  magnesium_mg double precision,
  phosphorus_mg double precision,
  potassium_mg double precision,
  sodium_mg double precision,
  zinc_mg double precision,
  copper_mg double precision,
  manganese_mg double precision,
  selenium_ug double precision,
  iodine_ug double precision,
  chromium_ug double precision,
  molybdenum_ug double precision,
  histidine_g double precision,
  isoleucine_g double precision,
  leucine_g double precision,
  lysine_g double precision,
  methionine_g double precision,
  phenylalanine_g double precision,
  threonine_g double precision,
  tryptophan_g double precision,
  valine_g double precision,
  alanine_g double precision,
  arginine_g double precision,
  aspartic_acid_g double precision,
  cysteine_g double precision,
  glutamic_acid_g double precision,
  glycine_g double precision,
  proline_g double precision,
  serine_g double precision,
  tyrosine_g double precision,
  caffeine_mg double precision,
  betaine_mg double precision,
  lutein_zeaxanthin_ug double precision,
  ingredients_text text,
  raw_payload jsonb,
  verified boolean not null default false,
  is_complete boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists ux_food_items_source_source_id
  on public.food_items (source, source_id)
  where source_id is not null;

create unique index if not exists ux_food_items_source_barcode
  on public.food_items (source, barcode)
  where barcode is not null;

create index if not exists idx_food_items_name
  on public.food_items (lower(name));

create index if not exists idx_food_items_barcode
  on public.food_items (barcode);

create index if not exists idx_food_items_updated
  on public.food_items (updated_at desc);

create table if not exists public.user_food_favorites (
  user_id uuid not null references public.profiles (id) on delete cascade,
  food_item_id bigint not null references public.food_items (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, food_item_id)
);

create index if not exists idx_user_food_favorites_user_created
  on public.user_food_favorites (user_id, created_at desc);

create table if not exists public.custom_recipes (
  id bigint generated by default as identity primary key,
  created_by_user_id uuid not null references public.profiles (id) on delete cascade,
  name text not null,
  description text,
  link_url text,
  prep_time_min double precision,
  cook_time_min double precision,
  servings double precision not null default 1 check (servings > 0),
  steps jsonb not null default '[]'::jsonb,
  ingredient_total_weight_g double precision,
  prepared_food_weight_g double precision,
  effective_recipe_weight_g double precision,
  grams_per_serving double precision,
  calories_per_serving double precision,
  protein_g_per_serving double precision,
  carbs_g_per_serving double precision,
  fat_g_per_serving double precision,
  is_public boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint custom_recipes_steps_is_array check (jsonb_typeof(steps) = 'array')
);

create index if not exists idx_custom_recipes_creator_updated
  on public.custom_recipes (created_by_user_id, updated_at desc);

create index if not exists idx_custom_recipes_public_updated
  on public.custom_recipes (is_public, updated_at desc);

create index if not exists idx_custom_recipes_name
  on public.custom_recipes (lower(name));

create table if not exists public.custom_recipe_ingredients (
  id bigint generated by default as identity primary key,
  recipe_id bigint not null references public.custom_recipes (id) on delete cascade,
  food_item_id bigint not null references public.food_items (id),
  amount_value double precision not null check (amount_value > 0),
  amount_unit text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_custom_recipe_ingredients_recipe_sort
  on public.custom_recipe_ingredients (recipe_id, sort_order asc, id asc);

create table if not exists public.custom_meals (
  id bigint generated by default as identity primary key,
  created_by_user_id uuid not null references public.profiles (id) on delete cascade,
  name text not null,
  description text,
  servings double precision not null default 1 check (servings > 0),
  total_weight_g double precision,
  grams_per_serving double precision,
  calories_per_serving double precision,
  protein_g_per_serving double precision,
  carbs_g_per_serving double precision,
  fat_g_per_serving double precision,
  is_public boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_custom_meals_creator_updated
  on public.custom_meals (created_by_user_id, updated_at desc);

create index if not exists idx_custom_meals_public_updated
  on public.custom_meals (is_public, updated_at desc);

create index if not exists idx_custom_meals_name
  on public.custom_meals (lower(name));

create table if not exists public.custom_meal_items (
  id bigint generated by default as identity primary key,
  meal_id bigint not null references public.custom_meals (id) on delete cascade,
  food_item_id bigint not null references public.food_items (id),
  amount_value double precision not null check (amount_value > 0),
  amount_unit text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_custom_meal_items_meal_sort
  on public.custom_meal_items (meal_id, sort_order asc, id asc);

create table if not exists public.user_food_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  entry_type text not null check (
    entry_type in ('food_item', 'custom_recipe', 'custom_meal', 'quick_add')
  ),
  food_item_id bigint references public.food_items (id) on delete set null,
  custom_recipe_id bigint references public.custom_recipes (id) on delete set null,
  custom_meal_id bigint references public.custom_meals (id) on delete set null,
  date date not null,
  logged_at timestamptz not null default now(),
  meal_type text,
  amount_value double precision not null default 1 check (amount_value > 0),
  amount_unit text not null default 'g',
  resolved_quantity_g double precision,
  display_name text not null,
  calories double precision not null default 0,
  protein_g double precision not null default 0,
  carbs_g double precision not null default 0,
  fat_g double precision not null default 0,
  alcohol_g double precision not null default 0,
  system_calculated_calories double precision,
  is_energy_manually_set boolean not null default false,
  metadata jsonb,
  created_at timestamptz not null default now(),
  constraint user_food_entries_target_matches_type check (
    (
      entry_type = 'food_item'
      and food_item_id is not null
      and custom_recipe_id is null
      and custom_meal_id is null
    )
    or (
      entry_type = 'custom_recipe'
      and food_item_id is null
      and custom_recipe_id is not null
      and custom_meal_id is null
    )
    or (
      entry_type = 'custom_meal'
      and food_item_id is null
      and custom_recipe_id is null
      and custom_meal_id is not null
    )
    or (
      entry_type = 'quick_add'
      and food_item_id is null
      and custom_recipe_id is null
      and custom_meal_id is null
    )
  )
);

create index if not exists idx_user_food_entries_user_date_logged_at
  on public.user_food_entries (user_id, date desc, logged_at asc);

create index if not exists idx_user_food_entries_user_created
  on public.user_food_entries (user_id, created_at desc);

create table if not exists public.user_diary_days (
  user_id uuid not null references public.profiles (id) on delete cascade,
  date date not null,
  is_complete boolean not null default false,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, date)
);

create index if not exists idx_user_diary_days_user_date
  on public.user_diary_days (user_id, date desc);

create table if not exists public.weight_entries (
  id text primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  measured_at timestamptz not null,
  measured_at_local_iso text not null,
  measured_day_local date generated always as (
    public.iso_text_date_prefix(measured_at_local_iso)
  ) stored,
  zone_offset_minutes integer not null,
  value_kg double precision not null,
  value_original double precision not null,
  unit_original text not null default 'kg' check (unit_original = 'kg'),
  source text not null check (
    source in ('manual', 'import', 'smart_scale', 'healthkit', 'health_connect', 'google_fit', 'csv')
  ),
  notes text,
  tags jsonb not null default '[]'::jsonb,
  client_generated_id text not null,
  device_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  version integer not null default 1,
  sync_status text not null default 'synced' check (sync_status in ('pending', 'synced', 'error')),
  sync_error text,
  constraint weight_entries_tags_is_array check (jsonb_typeof(tags) = 'array')
);

create index if not exists idx_weight_entries_user_measured_at
  on public.weight_entries (user_id, measured_at desc);

create index if not exists idx_weight_entries_user_deleted_at
  on public.weight_entries (user_id, deleted_at);

create unique index if not exists ux_weight_entries_user_client_generated_id
  on public.weight_entries (user_id, client_generated_id);

create unique index if not exists ux_weight_entries_one_active_per_local_day
  on public.weight_entries (user_id, measured_day_local)
  where deleted_at is null;

create table if not exists public.weight_goals (
  user_id uuid primary key references public.profiles (id) on delete cascade,
  target_weight_kg double precision not null,
  target_date date,
  goal_band_kg double precision not null default 0.3,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  type text not null,
  duration_min double precision,
  calories_burned double precision,
  date date not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_activities_user_date
  on public.activities (user_id, date desc);

create table if not exists public.adaptive_calorie_recommendations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  status text not null default 'proposed' check (
    status in ('proposed', 'accepted', 'rejected', 'applied', 'superseded')
  ),
  algorithm_version text not null default 'v1',
  window_start date not null,
  window_end date not null,
  confidence text not null check (
    confidence in ('low', 'medium', 'high')
  ),
  current_base_calories integer,
  recommended_base_calories integer not null,
  estimated_tdee integer not null,
  recommended_delta integer not null,
  avg_logged_calories double precision not null,
  complete_days_used integer not null check (complete_days_used >= 0),
  weigh_ins_used integer not null check (weigh_ins_used >= 0),
  trend_start_kg double precision not null,
  trend_end_kg double precision not null,
  observed_weekly_change_kg double precision,
  reason text not null,
  input_summary jsonb,
  responded_at timestamptz,
  applied_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint adaptive_calorie_recommendations_window_valid
    check (window_end >= window_start)
);

create index if not exists idx_adaptive_calorie_recommendations_user_created
  on public.adaptive_calorie_recommendations (user_id, created_at desc);

create index if not exists idx_adaptive_calorie_recommendations_user_status
  on public.adaptive_calorie_recommendations (user_id, status, created_at desc);

create unique index if not exists ux_adaptive_calorie_recommendations_one_open
  on public.adaptive_calorie_recommendations (user_id)
  where status = 'proposed';

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists trg_user_settings_updated_at on public.user_settings;
create trigger trg_user_settings_updated_at
before update on public.user_settings
for each row execute function public.set_updated_at();

drop trigger if exists trg_food_items_updated_at on public.food_items;
create trigger trg_food_items_updated_at
before update on public.food_items
for each row execute function public.set_updated_at();

drop trigger if exists trg_custom_recipes_updated_at on public.custom_recipes;
create trigger trg_custom_recipes_updated_at
before update on public.custom_recipes
for each row execute function public.set_updated_at();

drop trigger if exists trg_custom_meals_updated_at on public.custom_meals;
create trigger trg_custom_meals_updated_at
before update on public.custom_meals
for each row execute function public.set_updated_at();

drop trigger if exists trg_weight_entries_updated_at on public.weight_entries;
create trigger trg_weight_entries_updated_at
before update on public.weight_entries
for each row execute function public.set_updated_at();

drop trigger if exists trg_user_diary_days_updated_at on public.user_diary_days;
create trigger trg_user_diary_days_updated_at
before update on public.user_diary_days
for each row execute function public.set_updated_at();

drop trigger if exists trg_weight_goals_updated_at on public.weight_goals;
create trigger trg_weight_goals_updated_at
before update on public.weight_goals
for each row execute function public.set_updated_at();

drop trigger if exists trg_adaptive_calorie_recommendations_updated_at on public.adaptive_calorie_recommendations;
create trigger trg_adaptive_calorie_recommendations_updated_at
before update on public.adaptive_calorie_recommendations
for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.user_settings enable row level security;
alter table public.food_items enable row level security;
alter table public.user_food_favorites enable row level security;
alter table public.custom_recipes enable row level security;
alter table public.custom_recipe_ingredients enable row level security;
alter table public.custom_meals enable row level security;
alter table public.custom_meal_items enable row level security;
alter table public.user_food_entries enable row level security;
alter table public.user_diary_days enable row level security;
alter table public.weight_entries enable row level security;
alter table public.weight_goals enable row level security;
alter table public.activities enable row level security;
alter table public.adaptive_calorie_recommendations enable row level security;

drop policy if exists profiles_self_select on public.profiles;
create policy profiles_self_select
on public.profiles for select
using (id = auth.uid());

drop policy if exists profiles_self_insert on public.profiles;
create policy profiles_self_insert
on public.profiles for insert
with check (id = auth.uid());

drop policy if exists profiles_self_update on public.profiles;
create policy profiles_self_update
on public.profiles for update
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists user_settings_self_all on public.user_settings;
create policy user_settings_self_all
on public.user_settings for all
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists food_items_read_authenticated on public.food_items;
create policy food_items_read_authenticated
on public.food_items for select
using (auth.uid() is not null);

drop policy if exists food_items_insert_submitter on public.food_items;
create policy food_items_insert_submitter
on public.food_items for insert
with check (
  auth.uid() is not null
  and submitted_by_user_id = auth.uid()
);

drop policy if exists user_food_favorites_self_select on public.user_food_favorites;
create policy user_food_favorites_self_select
on public.user_food_favorites for select
using (user_id = auth.uid());

drop policy if exists user_food_favorites_self_insert on public.user_food_favorites;
create policy user_food_favorites_self_insert
on public.user_food_favorites for insert
with check (
  user_id = auth.uid()
  and exists (
    select 1
    from public.food_items f
    where f.id = food_item_id
  )
);

drop policy if exists user_food_favorites_self_delete on public.user_food_favorites;
create policy user_food_favorites_self_delete
on public.user_food_favorites for delete
using (user_id = auth.uid());

drop policy if exists custom_recipes_read_public_or_creator on public.custom_recipes;
create policy custom_recipes_read_public_or_creator
on public.custom_recipes for select
using (is_public or created_by_user_id = auth.uid());

drop policy if exists custom_recipes_insert_creator on public.custom_recipes;
create policy custom_recipes_insert_creator
on public.custom_recipes for insert
with check (created_by_user_id = auth.uid());

drop policy if exists custom_recipes_update_creator on public.custom_recipes;
create policy custom_recipes_update_creator
on public.custom_recipes for update
using (created_by_user_id = auth.uid())
with check (created_by_user_id = auth.uid());

drop policy if exists custom_recipes_delete_creator on public.custom_recipes;
create policy custom_recipes_delete_creator
on public.custom_recipes for delete
using (created_by_user_id = auth.uid());

drop policy if exists custom_recipe_ingredients_read_visible_recipe on public.custom_recipe_ingredients;
create policy custom_recipe_ingredients_read_visible_recipe
on public.custom_recipe_ingredients for select
using (
  exists (
    select 1
    from public.custom_recipes r
    where r.id = recipe_id
      and (r.is_public or r.created_by_user_id = auth.uid())
  )
);

drop policy if exists custom_recipe_ingredients_modify_creator_recipe on public.custom_recipe_ingredients;
create policy custom_recipe_ingredients_modify_creator_recipe
on public.custom_recipe_ingredients for all
using (
  exists (
    select 1
    from public.custom_recipes r
    where r.id = recipe_id
      and r.created_by_user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.custom_recipes r
    where r.id = recipe_id
      and r.created_by_user_id = auth.uid()
  )
);

drop policy if exists custom_meals_read_public_or_creator on public.custom_meals;
create policy custom_meals_read_public_or_creator
on public.custom_meals for select
using (is_public or created_by_user_id = auth.uid());

drop policy if exists custom_meals_insert_creator on public.custom_meals;
create policy custom_meals_insert_creator
on public.custom_meals for insert
with check (created_by_user_id = auth.uid());

drop policy if exists custom_meals_update_creator on public.custom_meals;
create policy custom_meals_update_creator
on public.custom_meals for update
using (created_by_user_id = auth.uid())
with check (created_by_user_id = auth.uid());

drop policy if exists custom_meals_delete_creator on public.custom_meals;
create policy custom_meals_delete_creator
on public.custom_meals for delete
using (created_by_user_id = auth.uid());

drop policy if exists custom_meal_items_read_visible_meal on public.custom_meal_items;
create policy custom_meal_items_read_visible_meal
on public.custom_meal_items for select
using (
  exists (
    select 1
    from public.custom_meals m
    where m.id = meal_id
      and (m.is_public or m.created_by_user_id = auth.uid())
  )
);

drop policy if exists custom_meal_items_modify_creator_meal on public.custom_meal_items;
create policy custom_meal_items_modify_creator_meal
on public.custom_meal_items for all
using (
  exists (
    select 1
    from public.custom_meals m
    where m.id = meal_id
      and m.created_by_user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.custom_meals m
    where m.id = meal_id
      and m.created_by_user_id = auth.uid()
  )
);

drop policy if exists user_food_entries_self_select on public.user_food_entries;
create policy user_food_entries_self_select
on public.user_food_entries for select
using (user_id = auth.uid());

drop policy if exists user_food_entries_self_insert on public.user_food_entries;
create policy user_food_entries_self_insert
on public.user_food_entries for insert
with check (
  user_id = auth.uid()
  and (
    entry_type = 'quick_add'
    or (
      entry_type = 'food_item'
      and exists (
        select 1
        from public.food_items f
        where f.id = food_item_id
      )
    )
    or (
      entry_type = 'custom_recipe'
      and exists (
        select 1
        from public.custom_recipes r
        where r.id = custom_recipe_id
          and (r.is_public or r.created_by_user_id = auth.uid())
      )
    )
    or (
      entry_type = 'custom_meal'
      and exists (
        select 1
        from public.custom_meals m
        where m.id = custom_meal_id
          and (m.is_public or m.created_by_user_id = auth.uid())
      )
    )
  )
);

drop policy if exists user_food_entries_self_update on public.user_food_entries;
create policy user_food_entries_self_update
on public.user_food_entries for update
using (user_id = auth.uid())
with check (
  user_id = auth.uid()
  and (
    entry_type = 'quick_add'
    or (
      entry_type = 'food_item'
      and exists (
        select 1
        from public.food_items f
        where f.id = food_item_id
      )
    )
    or (
      entry_type = 'custom_recipe'
      and exists (
        select 1
        from public.custom_recipes r
        where r.id = custom_recipe_id
          and (r.is_public or r.created_by_user_id = auth.uid())
      )
    )
    or (
      entry_type = 'custom_meal'
      and exists (
        select 1
        from public.custom_meals m
        where m.id = custom_meal_id
          and (m.is_public or m.created_by_user_id = auth.uid())
      )
    )
  )
);

drop policy if exists user_food_entries_self_delete on public.user_food_entries;
create policy user_food_entries_self_delete
on public.user_food_entries for delete
using (user_id = auth.uid());

drop policy if exists user_diary_days_self_all on public.user_diary_days;
create policy user_diary_days_self_all
on public.user_diary_days for all
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists weight_entries_self_all on public.weight_entries;
create policy weight_entries_self_all
on public.weight_entries for all
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists weight_goals_self_all on public.weight_goals;
create policy weight_goals_self_all
on public.weight_goals for all
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists activities_self_all on public.activities;
create policy activities_self_all
on public.activities for all
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists adaptive_calorie_recommendations_self_all on public.adaptive_calorie_recommendations;
create policy adaptive_calorie_recommendations_self_all
on public.adaptive_calorie_recommendations for all
using (user_id = auth.uid())
with check (user_id = auth.uid());

-- Optional convenience backfill after creating the schema:
-- insert into public.profiles (id, email)
-- select id, email from auth.users
-- on conflict (id) do nothing;
